/*! @license MIT ©2015-2018 Ruben Verborgh and Ruben Taelman, Ghent University - imec */
/** A QuadPatternFragmentsController responds to requests for TPFs and QPFs */

import LdfCore = require('@ldf/core');
import url = require('url');
import _ = require('lodash');
import type Datasource = require('@ldf/core/lib/datasources/Datasource');
import type Controller_ = require('@ldf/core/lib/controllers/Controller');
import type { LdfRequest, LdfResponse, Query, RouterRequest } from '@ldf/core/lib/types';
import type { Quad } from 'n3';
import type { FragmentInfo, FragmentMetadata, FragmentQuery, FragmentRouter, QuadPatternFragmentsControllerOptions } from '../types';

const Controller = LdfCore.controllers.Controller;

// Creates a new QuadPatternFragmentsController
class QuadPatternFragmentsController extends Controller {
  protected _routers: FragmentRouter[];
  protected _extensions: Controller_[];
  public viewName: string;

  constructor(options?: QuadPatternFragmentsControllerOptions) {
    options = options || {};
    super(options);
    this._routers = options.routers || [];
    this._extensions = options.extensions || [];

    this.viewName = 'QuadPatternFragments';
  }

  // The required features the given datasource must have
  supportsDatasource(datasource: Datasource) {
    return datasource.supportedFeatures.triplePattern ||
          datasource.supportedFeatures.quadPattern;
  }

  // Try to serve the requested fragment
  override _handleRequest(request: LdfRequest, response: LdfResponse, next: (error?: Error) => void) {
    // Create the query from the request by calling the fragment routers
    let requestParams: RouterRequest = { url: request.parsedUrl as RouterRequest['url'], headers: request.headers },
        query: Query = this._routers.reduce((query: Query, router: FragmentRouter) => {
          try { router.extractQueryParams(requestParams, query); }
          catch (e) { /* ignore routing errors */ }
          return query;
        }, { features: {} } as Query);

    // Execute the query on the data source
    let datasource = query.features!.datasource && this._datasources[query.datasource!];
    delete query.features!.datasource;
    if (!datasource || !datasource.supportsQuery(query) ||
      !this.supportsDatasource(datasource))
      return next();

    // Generate the query result
    let view = this._negotiateView(this.viewName, request, response),
        settings = this._createFragmentMetadata(request, query, datasource);
    settings.results = datasource.select(query,
      (error?: Error) => { error && next(error); }) as import('asynciterator').AsyncIterator<Quad> | undefined;

    // Execute the extensions and render the query result
    let extensions = this._extensions, extensionId = 0;
    (function nextExtension(error?: Error) {
      // Log a possible error with the previous extension
      if (error)
        process.stderr.write(error.stack + '\n');
      // Execute the next extension
      if (extensionId < extensions.length)
        extensions[extensionId++].handleRequest(request, response, nextExtension, settings);
      // Render the query result
      else
        view.render(settings, request, response);
    })();
  }

  // Create the template URL for requesting quad patterns
  _createTemplateUrl(datasourceUrl: string, supportsQuads: boolean) {
    return datasourceUrl + (!supportsQuads ? '{?subject,predicate,object}' :
      '{?subject,predicate,object,graph}');
  }

  // Create parameterized pattern string for quad patterns
  _createPatternString(query: Query, supportsQuads: boolean) {
    let subject = query.subject, predicate = query.predicate,
        graph: string = '';
    // Serialize subject and predicate IRIs or variables
    let subjectStr   = subject   ? '<' + query.subject!.value   + '> ' : '?s ';
    let predicateStr = predicate ? '<' + query.predicate!.value + '> ' : '?p ';
    // Serialize object IRI, literal, or variable
    let objectStr: string;
    if (query.object && query.object.termType === 'NamedNode')
      objectStr = '<' + query.object.value + '> ';
    else
      objectStr = query.object ? query.object.value : '?o';
    // Serialize graph IRI default graph, or variable
    if (supportsQuads) {
      let graphTerm = query.graph;
      if (graphTerm && graphTerm.termType === 'DefaultGraph') graph = ' @default';
      else if (graphTerm)   graph = ' <' + graphTerm.value + '>';
      else              graph = ' ?g';
    }
    // Join them in a pattern
    return '{ ' + subjectStr + predicateStr + objectStr + graph + '. }';
  }

  // Creates metadata about the requested fragment
  _createFragmentMetadata(request: LdfRequest, query: Query, datasourceSettings: Datasource): FragmentMetadata {
    // TODO: these URLs should be generated by the routers
    let requestUrl = request.parsedUrl!,
        // maintain the originally requested query string to avoid encoding differences
        origQuery = request.url!.replace(/[^?]+/, ''),
        pageUrl = url.format(requestUrl).replace(/\?.*/, origQuery),
        paramsNoPage = _.omit(requestUrl.query as Record<string, unknown>, 'page') as import('querystring').ParsedUrlQueryInput,
        currentPage = parseInt((requestUrl.query as { page?: string }).page!, 10) || 1,
        datasourceUrl = url.format(_.omit(requestUrl, 'query')),
        fragmentUrl = url.format({ ...requestUrl, query: paramsNoPage }),
        fragmentPageUrlBase = fragmentUrl + (/\?/.test(fragmentUrl) ? '&' : '?') + 'page=',
        indexUrl = url.format(_.omit(requestUrl, 'search', 'query', 'pathname')) + '/';

    // Generate a textual representation of the pattern
    let supportsQuads = datasourceSettings.supportedFeatures.quadPattern || false;
    (query as FragmentQuery).patternString = this._createPatternString(query, supportsQuads);

    let fragment: FragmentInfo = {
      url: fragmentUrl,
      pageUrl: pageUrl,
      firstPageUrl: fragmentPageUrlBase + '1',
      nextPageUrl: fragmentPageUrlBase + (currentPage + 1),
      previousPageUrl: currentPage > 1 ? fragmentPageUrlBase + (currentPage - 1) : null,
    };

    return {
      datasource: _.assign(datasourceSettings, {
        index: indexUrl + '#dataset',
        url: datasourceUrl + '#dataset',
        templateUrl: this._createTemplateUrl(datasourceUrl, supportsQuads),
        supportsQuads: supportsQuads,
      }),
      fragment,
      query,
      prefixes: this._prefixes,
      datasources: this._datasources,
    };
  }

  // Close all data sources
  override close() {
    for (let datasourceName in this._datasources) {
      try { this._datasources[datasourceName].close(); }
      catch (error) { /* ignore closing errors */ }
    }
  }
}

export = QuadPatternFragmentsController;
