/*! @license MIT ©2015-2016 Ruben Verborgh, Ghent University - imec */
/* A SummaryHtmlViewExtension extends the Quad Pattern Fragments RDF view with a summary link. */

import LdfCore = require('@ldf/core');
import * as path from 'path';

const HtmlView = LdfCore.views.HtmlView;

// Creates a new SummaryHtmlViewExtension
class SummaryHtmlViewExtension extends HtmlView {
  constructor(settings?: any) {
    super('QuadPatternFragments:Before', settings);
  }

  // Renders the view with the given settings to the response
  override _render(settings: any, request: any, response: any, done: any) {
    // If summaries are enabled, connect the datasource to its summary
    // TODO: summary should be of/off per dataset
    if (settings.summaries && (settings.summaries.dir || settings.summaries.path)) {
      // TODO: summary URL should be generated by router
      settings.summary = {
        url: settings.baseURL + 'summaries' + encodeURIComponent(settings.query.datasource),
      };
      this._renderTemplate(path.join(__dirname, 'summary-link'), settings, request, response, done);
    }
    else
      done();
  }
}


export = SummaryHtmlViewExtension;
